---

- name: Install etckeeper package
  yum: name=etckeeper state=present

- name: Disable autocommits
  lineinfile: dest=/etc/etckeeper/etckeeper.conf
              regexp=^#?{{ item }}=
              line={{ item }}=1
  with_items:
   - AVOID_DAILY_AUTOCOMMITS
   - AVOID_COMMIT_BEFORE_INSTALL

- name: Prepare initial commit
  command: etckeeper init
  args:
    creates: /etc/.git
  register: etckeeper

- name: Set user email for the repo
  command: etckeeper vcs config --local user.email root@localhost
  when: etckeeper.changed

- name: Ignore some config files
  lineinfile: dest=/etc/.gitignore
              line={{ item }}
              state=present
  with_items: "{{etckeeper_ignored}}"
  when: etckeeper.changed

- name: Remove some config files from git cache
  command: etckeeper vcs rm --cached {{ item }}
  with_items: "{{etckeeper_ignored}}"
  when: etckeeper.changed

- name: Initial etckeeper commit
  command: etckeeper commit "initial commit"
  when: etckeeper.changed
